version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=auth_user
      - DB_PASSWORD=securepassword
      - DB_NAME=auth_db
      - SECRET_KEY=your-secure-secret-key-here
    depends_on:
      - mariadb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    ports:
      - "80:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend

  mariadb:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data: