version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app  # Mount the backend code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=auth_user
      - DB_PASSWORD=securepassword
      - DB_NAME=auth_db
      - SECRET_KEY=your-secure-secret-key-here
      - MONGO_URI=${MONGO_ATLAS_URI:-mongodb+srv://username:password@your-cluster.mongodb.net/guessucla}
    depends_on:
      - mariadb
    env_file:
      - ./.env.dev

  geo_db:
    build:
      context: .
      dockerfile: backend/Dockerfile  # Same Dockerfile as backend
    volumes:
      - ./backend:/app  # Mount the backend code
    command: ["uvicorn", "geo_db:geo_db", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    env_file:
      - .env  # Load MongoDB URI securely
    depends_on:
      - backend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app  # Mount the frontend code
      - /app/node_modules  # Preserve node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  mariadb:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
